-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "auth"."mad_feed_votes" add column "ranking" numeric
--  not null default '0';
