import type {
  SECURE_EVM_EVENTS,
  SECURE_EVM_GET_ACCOUNTS,
  SECURE_EVM_PREVIEW_PUBLIC_KEYS,
  SECURE_EVM_PROVIDER_SEND,
  SECURE_EVM_REQUEST_ACCOUNTS,
  SECURE_EVM_SHOULD_BE_METAMASK,
  SECURE_EVM_SIGN_MESSAGE,
  SECURE_EVM_SIGN_TX,
} from "./services/evm/events";
import type {
  LEDGER_EVM_SIGN_MESSAGE,
  LEDGER_EVM_SIGN_TX,
  LEDGER_SVM_SIGN_MESSAGE,
  LEDGER_SVM_SIGN_TX,
  SECURE_LEDGER_EVENTS,
} from "./services/ledger/events";
import type {
  SECURE_SVM_CONNECT,
  SECURE_SVM_DISCONNECT,
  SECURE_SVM_EVENTS,
  SECURE_SVM_PREVIEW_PUBLIC_KEYS,
  SECURE_SVM_SIGN_ALL_TX,
  SECURE_SVM_SIGN_MESSAGE,
  SECURE_SVM_SIGN_TX,
} from "./services/svm/events";
import type {
  SECURE_USER_APPROVE_ORIGIN,
  SECURE_USER_CHECK_PASSWORD,
  SECURE_USER_EVENTS,
  SECURE_USER_EXPORT_BACKUP,
  SECURE_USER_GET,
  SECURE_USER_GET_ALL,
  SECURE_USER_GET_ALL_WITH_ACCOUNTS,
  SECURE_USER_GET_KEYRING_STATE,
  SECURE_USER_GET_MNEMONIC,
  SECURE_USER_IMPORT_BACKUP,
  SECURE_USER_INIT_WALLET,
  SECURE_USER_PING,
  SECURE_USER_REMOVE_ORIGIN,
  SECURE_USER_RESET_BACKPACK,
  SECURE_USER_SET_ACTIVE,
  SECURE_USER_SET_WALLET,
  SECURE_USER_UNLOCK_KEYRING,
  SECURE_USER_UPDATE,
  SECURE_USER_UPDATE_PREFERENCES,
} from "./services/user/events";

export type { SECURE_EVM_EVENTS } from "./services/evm/events";
export type { SECURE_LEDGER_EVENTS } from "./services/ledger/events";
export type { SECURE_SVM_EVENTS } from "./services/svm/events";
export type { SECURE_USER_EVENTS } from "./services/user/events";

export type SECURE_EVENTS =
  | SECURE_EVM_EVENTS
  | SECURE_SVM_EVENTS
  | SECURE_USER_EVENTS
  | SECURE_LEDGER_EVENTS;

export type SecureEvent<T extends SECURE_EVENTS = SECURE_EVENTS> =
  T extends "SECURE_SVM_SIGN_MESSAGE"
    ? SECURE_SVM_SIGN_MESSAGE
    : T extends "SECURE_SVM_SIGN_TX"
    ? SECURE_SVM_SIGN_TX
    : T extends "SECURE_SVM_SIGN_ALL_TX"
    ? SECURE_SVM_SIGN_ALL_TX
    : T extends "SECURE_SVM_CONNECT"
    ? SECURE_SVM_CONNECT
    : T extends "SECURE_SVM_DISCONNECT"
    ? SECURE_SVM_DISCONNECT
    : T extends "SECURE_SVM_PREVIEW_PUBLIC_KEYS"
    ? SECURE_SVM_PREVIEW_PUBLIC_KEYS
    : T extends "SECURE_EVM_SIGN_MESSAGE"
    ? SECURE_EVM_SIGN_MESSAGE
    : T extends "SECURE_EVM_GET_ACCOUNTS"
    ? SECURE_EVM_GET_ACCOUNTS
    : T extends "SECURE_EVM_SHOULD_BE_METAMASK"
    ? SECURE_EVM_SHOULD_BE_METAMASK
    : T extends "SECURE_EVM_REQUEST_ACCOUNTS"
    ? SECURE_EVM_REQUEST_ACCOUNTS
    : T extends "SECURE_EVM_SIGN_TX"
    ? SECURE_EVM_SIGN_TX
    : T extends "SECURE_EVM_PROVIDER_SEND"
    ? SECURE_EVM_PROVIDER_SEND
    : T extends "SECURE_EVM_PREVIEW_PUBLIC_KEYS"
    ? SECURE_EVM_PREVIEW_PUBLIC_KEYS
    : T extends "SECURE_USER_RESET_BACKPACK"
    ? SECURE_USER_RESET_BACKPACK
    : T extends "SECURE_USER_PING"
    ? SECURE_USER_PING
    : T extends "SECURE_USER_UNLOCK_KEYRING"
    ? SECURE_USER_UNLOCK_KEYRING
    : T extends "SECURE_USER_GET_MNEMONIC"
    ? SECURE_USER_GET_MNEMONIC
    : T extends "SECURE_USER_APPROVE_ORIGIN"
    ? SECURE_USER_APPROVE_ORIGIN
    : T extends "SECURE_USER_REMOVE_ORIGIN"
    ? SECURE_USER_REMOVE_ORIGIN
    : T extends "SECURE_USER_CHECK_PASSWORD"
    ? SECURE_USER_CHECK_PASSWORD
    : T extends "SECURE_USER_SET_ACTIVE"
    ? SECURE_USER_SET_ACTIVE
    : T extends "SECURE_USER_SET_WALLET"
    ? SECURE_USER_SET_WALLET
    : T extends "SECURE_USER_UPDATE"
    ? SECURE_USER_UPDATE
    : T extends "SECURE_USER_EXPORT_BACKUP"
    ? SECURE_USER_EXPORT_BACKUP
    : T extends "SECURE_USER_IMPORT_BACKUP"
    ? SECURE_USER_IMPORT_BACKUP
    : T extends "SECURE_USER_UPDATE_PREFERENCES"
    ? SECURE_USER_UPDATE_PREFERENCES
    : T extends "SECURE_USER_GET"
    ? SECURE_USER_GET
    : T extends "SECURE_USER_GET_ALL"
    ? SECURE_USER_GET_ALL
    : T extends "SECURE_USER_GET_ALL_WITH_ACCOUNTS"
    ? SECURE_USER_GET_ALL_WITH_ACCOUNTS
    : T extends "SECURE_USER_GET_KEYRING_STATE"
    ? SECURE_USER_GET_KEYRING_STATE
    : T extends "SECURE_USER_INIT_WALLET"
    ? SECURE_USER_INIT_WALLET
    : T extends "LEDGER_SVM_SIGN_TX"
    ? LEDGER_SVM_SIGN_TX
    : T extends "LEDGER_EVM_SIGN_TX"
    ? LEDGER_EVM_SIGN_TX
    : T extends "LEDGER_SVM_SIGN_MESSAGE"
    ? LEDGER_SVM_SIGN_MESSAGE
    : T extends "LEDGER_EVM_SIGN_MESSAGE"
    ? LEDGER_EVM_SIGN_MESSAGE
    : never;
