import type {
  NOTIFICATION_KEYRING_STORE_LOCKED,
  NOTIFICATION_KEYRING_STORE_UNLOCKED,
  NOTIFICATION_USER_UPDATED,
  SECURE_USER_NOTIFICATIONS,
} from "./services/user/notifications";

export type { SECURE_USER_NOTIFICATIONS } from "./services/user/notifications";

export type SECURE_NOTIFICATIONS = SECURE_USER_NOTIFICATIONS;

export type SecureNotification<
  T extends SECURE_NOTIFICATIONS = SECURE_NOTIFICATIONS
> = T extends "NOTIFICATION_USER_UPDATED"
  ? NOTIFICATION_USER_UPDATED
  : T extends "NOTIFICATION_KEYRING_STORE_UNLOCKED"
  ? NOTIFICATION_KEYRING_STORE_UNLOCKED
  : T extends "NOTIFICATION_KEYRING_STORE_LOCKED"
  ? NOTIFICATION_KEYRING_STORE_LOCKED
  : never;
