-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "auth"."friendships" add column "user2_last_read_message_id" text
--  null;
