name = "jupiter-proxy"
main = "src/index.ts"
compatibility_date = "2023-01-07"

[vars]
DEFAULT_FEE_BPS = 85
TOKEN_PROGRAM_ADDRESS = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
FEE_AUTHORITY_ADDRESS = "7vNrxNhWJjELWexsgRJTpPhx2cEnV3ksBWsd7yo6kUEi"
RPC = "https://rpc-proxy.backpack.workers.dev"
