-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "auth"."users" add column "waolist_tokens_eligible" integer
--  not null default '1';
