-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "appstore"."pending_curator_reviews" add column "ix_keys" jsonb
--  not null;
