-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "auth"."friendships" add column "user1_blocked_user2" boolean
--  not null default 'false';
