-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "auth"."user_nfts" add column "blockchain" text
--  null default 'solana';
