-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "auth"."users" add column "is_internal" boolean
--  not null default 'false';
