name = "nft-data"
main = "src/index.ts"
compatibility_date = "2022-12-05"
node_compat = true

services = [
  { binding = "solanaRpc", service = "rpc-proxy" },
  { binding = "ethereumRpc", service = "ethereum-rpc-proxy" }
]