-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."secure_transfer_transactions" add column "final_txn_signature" text
--  null;
