-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE VIEW "public"."mad_feed_user_score_totals" AS
--  SELECT users.id AS user_id,
--     rank() OVER (ORDER BY ((COALESCE(sum(mad_feed_post_vote_sums.comments_value), (0)::numeric)+COALESCE(mad_feed_user_promo_results.promotion_results_total, (0)::numeric) + COALESCE(mad_feed_user_promo_post_sums.promoted_total, (0)::numeric)) + COALESCE(sum(mad_feed_post_vote_sums.votes), (0)::numeric)) DESC) AS rank,
--     ((COALESCE(sum(mad_feed_post_vote_sums.comments_value), (0)::numeric)+COALESCE(mad_feed_user_promo_results.promotion_results_total, (0)::numeric) + COALESCE(mad_feed_user_promo_post_sums.promoted_total, (0)::numeric)) + COALESCE(sum(mad_feed_post_vote_sums.votes), (0)::numeric)) AS total_score,
--     COALESCE(sum(mad_feed_post_vote_sums.votes), (0)::numeric) AS total_post_votes_score,
--     COALESCE(mad_feed_user_promo_post_sums.promoted_total, (0)::numeric) AS total_promoted_score,
--     COALESCE(mad_feed_user_promo_results.promotion_results_total, (0)::numeric) AS total_promotion_results_score,
--     COALESCE(sum(mad_feed_post_vote_sums.comments_value), (0)::numeric) AS total_post_comments_score
--    FROM (((auth.users
--      LEFT JOIN mad_feed_post_vote_sums ON ((users.id = mad_feed_post_vote_sums.user_id)))
--      LEFT JOIN mad_feed_user_promo_post_sums ON ((users.id = mad_feed_user_promo_post_sums.user_id)))
--      LEFT JOIN mad_feed_user_promo_results ON ((users.id = mad_feed_user_promo_results.user_id)))
--   GROUP BY users.id, mad_feed_user_promo_post_sums.promoted_total, mad_feed_user_promo_results.promotion_results_total;
