name: app-mobile monorepo setup

runs:
  using: composite
  steps:
    - name: Check for EXPO_TOKEN
      shell: bash
      run: |
        if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
          echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
          exit 1
        fi

    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "yarn"

    - name: 🏗 Setup Expo
      uses: expo/expo-github-action@v7
      with:
        eas-version: latest
        # expo-version: ${{ inputs.expo-version }}
        token: ${{ secrets.EXPO_TOKEN }}

    - name: 📦 Install dependencies
      run: yarn install --frozen-lockfile --prefer-offline
      shell: bash
