name: app-mobile monorepo setup

inputs:
  eas-version:
    description: Version of EAS CLI to use
    default: latest

  expo-token:
    description: Expo token to authenticate with
    required: false

runs:
  using: composite
  steps:
    - name: 🏗 Setup Expo
      uses: expo/expo-github-action@v7
      with:
        eas-version: ${{ inputs.eas-version }}
        expo-version: ${{ inputs.expo-version }}
        token: ${{ inputs.expo-token }}
