name: app-mobile monorepo setup

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "yarn"

    - name: 🏗 Setup Expo
      uses: expo/expo-github-action@v7
      with:
        eas-version: latest
        # expo-version: ${{ inputs.expo-version }}
        token: ${{ secrets.EXPO_TOKEN }}

    - name: 📦 Install dependencies
      run: yarn install --frozen-lockfile --prefer-offline
      shell: bash
