name: Deploy backpack-ws
on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: "mv docker/backend-ws/Dockerfile ."

      - name: add secrets
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          cd backend/native/backend-ws
          touch .env
          printf 'NODE_ENV=production\n' >> .env
          printf 'AUTH_JWT=%s\n' '${{secrets.AUTH_JWT}}' >> .env
          printf 'AUTH_JWT_PRIVATE_KEY=%s\n' '${{secrets.AUTH_JWT_PRIVATE_KEY}}' >> .env
          printf 'AUTH_JWT_PUBLIC_KEY=%s\n' '${{secrets.AUTH_JWT_PUBLIC_KEY}}' >> .env
          printf 'AUTH_HASURA_URL=%s\n' '${{secrets.HASURA_URL}}' >> .env
          printf 'CHAT_HASURA_URL=%s\n' '${{secrets.CHAT_HASURA_URL}}' >> .env
          printf 'REDIS_URL=%s\n' '${{secrets.REDIS_URL}}' >> .env
          printf 'CHAT_JWT=%s\n' '${{secrets.CHAT_JWT}}' >> .env
          printf 'ALCHEMY_API_KEY=%s\n' '${{secrets.ALCHEMY_API_KEY}}' >> .env
          printf 'AWS_EB_SECRET_ACCESS_KEY=%s\n' '${{secrets.AWS_EB_SECRET_ACCESS_KEY}}' >> .env
          printf 'AWS_EB_SESSION_TOKEN=%s\n' '${{secrets.AWS_EB_SESSION_TOKEN}}' >> .env
          printf 'BUNDLEWATCH_GITHUB_TOKEN=%s\n' '${{secrets.BUNDLEWATCH_GITHUB_TOKEN}}' >> .env
          printf 'CHROME_CRX_PRIVATE_KEY=%s\n' '${{secrets.CHROME_CRX_PRIVATE_KEY}}' >> .env
          printf 'DISCORD_WEBHOOK=%s\n' '${{secrets.DISCORD_WEBHOOK}}' >> .env
          printf 'DOCKERHUB_TOKEN=%s\n' '${{secrets.DOCKERHUB_TOKEN}}' >> .env
          printf 'DOCKERHUB_USERNAME=%s\n' '${{secrets.DOCKERHUB_USERNAME}}' >> .env
          printf 'DOCKER_PASSWORD=%s\n' '${{secrets.DOCKER_PASSWORD}}' >> .env
          printf 'DOCKER_USERNAME=%s\n' '${{secrets.DOCKER_USERNAME}}' >> .env
          printf 'EXPO_TOKEN=%s\n' '${{secrets.EXPO_TOKEN}}' >> .env
          printf 'FLY_API_TOKEN=%s\n' '${{secrets.FLY_API_TOKEN}}' >> .env
          printf 'LEDGER_INJECTION_DEPLOY_KEY=%s\n' '${{secrets.LEDGER_INJECTION_DEPLOY_KEY}}' >> .env
          printf 'MAGIC_EDEN_API_KEY=%s\n' '${{secrets.MAGIC_EDEN_API_KEY}}' >> .env
          printf 'NPM_ACCESS_TOKEN=%s\n' '${{secrets.NPM_ACCESS_TOKEN}}' >> .env
          printf 'RATE_LIMIT_KEY=%s\n' '${{secrets.RATE_LIMIT_KEY}}' >> .env
          printf 'TURBO_SERVER_TOKEN=%s\n' '${{secrets.TURBO_SERVER_TOKEN}}' >> .env
          printf 'TURBO_TEAM=%s\n' '${{secrets.TURBO_TEAM}}' >> .env
          printf 'TURBO_TOKEN=%s\n' '${{secrets.TURBO_TOKEN}}' >> .env
          printf 'PORT=%s\n' '8080' >> .env
          cd ../../..

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the Docker image
        run: docker build . --tag backpackapp/backend-ws:${{ github.sha }}-ws

      - name: Docker Push
        run: docker push backpackapp/backend-ws:${{ github.sha }}-ws

      - name: Create zip
        run: "mkdir deploy && cp ./docker/backend-ws/docker-compose.yml ./deploy && cp ./docker/Dockerrun.aws.json ./deploy && sed 's/{{tag}}/${{ github.sha }}-ws/g' ./deploy/docker-compose.yml > ./deploy/temp.yml && mv ./deploy/temp.yml ./deploy/docker-compose.yml && cd deploy && zip deploy.zip * && cd .. && mv ./deploy/deploy.zip ."

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_EB_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_EB_SECRET_ACCESS_KEY }}
          application_name: backend-api
          environment_name: backend-ws-dockerhub-2
          version_label: ${{ github.sha }}-ws
          region: us-west-1
          deployment_package: deploy.zip
