import { blue100, blue800, darkColors, lightColors } from "./colorsv2";
// tamagui requires a specific format

export const color = {
  blue800,
  blue100,
  baseWhite: lightColors.baseWhite,
  lightAccentBlue: lightColors.lightAccentBlue,
  lightAccentBlueBackground: lightColors.lightAccentBlueBackground,
  lightAccentPurple: lightColors.lightAccentPurple,

  lightUser01: lightColors.lightUser01,
  lightUser02: lightColors.lightUser02,
  lightUser03: lightColors.lightUser03,
  lightUser04: lightColors.lightUser04,
  lightUser05: lightColors.lightUser05,
  lightUser06: lightColors.lightUser06,
  lightUser07: lightColors.lightUser07,
  lightUser08: lightColors.lightUser08,
  lightUser09: lightColors.lightUser09,
  lightUser10: lightColors.lightUser10,
  lightUser11: lightColors.lightUser11,
  lightUser12: lightColors.lightUser12,
  lightUser13: lightColors.lightUser13,
  lightUser14: lightColors.lightUser14,
  lightBaseBackgroundL0: lightColors.lightBaseBackgroundL0,
  lightBaseBackgroundL1: lightColors.lightBaseBackgroundL1,
  lightBaseBackgroundL2: lightColors.lightBaseBackgroundL2,
  lightBaseBorderLight: lightColors.lightBaseBorderLight,
  lightBaseBorderMed: lightColors.lightBaseBorderMed,
  lightBaseBorderFocus: lightColors.lightBaseBorderFocus,
  lightBaseDivider: lightColors.lightBaseDivider,
  lightBaseIcon: lightColors.lightBaseIcon,
  lightBaseIconHover: lightColors.lightBaseIconHover,
  lightBaseIconPress: lightColors.lightBaseIconPress,
  lightBaseTextHighEmphasis: lightColors.lightBaseTextHighEmphasis,
  lightBaseTextMedEmphasis: lightColors.lightBaseTextMedEmphasis,
  lightButtonPrimaryBackground: lightColors.lightButtonPrimaryBackground,
  lightButtonPrimaryText: lightColors.lightButtonPrimaryText,
  lightButtonSecondaryBackground: lightColors.lightButtonSecondaryBackground,
  lightButtonSecondaryText: lightColors.lightButtonSecondaryText,
  lightGreenBackgroundSolid: lightColors.lightGreenBackgroundSolid,
  lightGreenBackgroundTransparent: lightColors.lightGreenBackgroundTransparent,
  lightGreenBorder: lightColors.lightGreenBorder,
  lightGreenIcon: lightColors.lightGreenIcon,
  lightGreenText: lightColors.lightGreenText,
  lightRedBackgroundSolid: lightColors.lightRedBackgroundSolid,
  lightRedBackgroundTransparent: lightColors.lightRedBackgroundTransparent,
  lightRedBorder: lightColors.lightRedBorder,
  lightRedIcon: lightColors.lightRedIcon,
  lightRedText: lightColors.lightRedText,
  lightYellowBackgroundSolid: lightColors.lightYellowBackgroundSolid,
  lightYellowBackgroundTransparent:
    lightColors.lightYellowBackgroundTransparent,
  lightYellowBorder: lightColors.lightYellowBorder,
  lightYellowIcon: lightColors.lightYellowIcon,
  lightYellowText: lightColors.lightYellowText,

  darkAccentBlue: darkColors.darkAccentBlue,
  darkAccentBlueBackground: darkColors.darkAccentBlueBackground,
  darkAccentPurple: darkColors.darkAccentPurple,

  darkUser01: darkColors.darkUser01,
  darkUser02: darkColors.darkUser02,
  darkUser03: darkColors.darkUser03,
  darkUser04: darkColors.darkUser04,
  darkUser05: darkColors.darkUser05,
  darkUser06: darkColors.darkUser06,
  darkUser07: darkColors.darkUser07,
  darkUser08: darkColors.darkUser08,
  darkUser09: darkColors.darkUser09,
  darkUser10: darkColors.darkUser10,
  darkUser11: darkColors.darkUser11,
  darkUser12: darkColors.darkUser12,
  darkUser13: darkColors.darkUser13,
  darkUser14: darkColors.darkUser14,

  darkBaseBackgroundL0: darkColors.darkBaseBackgroundL0,
  darkBaseBackgroundL1: darkColors.darkBaseBackgroundL1,
  darkBaseBackgroundL2: darkColors.darkBaseBackgroundL2,
  darkBaseBorderLight: darkColors.darkBaseBorderLight,
  darkBaseBorderMed: darkColors.darkBaseBorderMed,
  darkBaseBorderFocus: darkColors.darkBaseBorderFocus,
  darkBaseDivider: darkColors.darkBaseDivider,
  darkBaseIcon: darkColors.darkBaseIcon,
  darkBaseIconHover: darkColors.darkBaseIconHover,
  darkBaseIconPress: darkColors.darkBaseIconPress,
  darkBaseTextHighEmphasis: darkColors.darkBaseTextHighEmphasis,
  darkBaseTextMedEmphasis: darkColors.darkBaseTextMedEmphasis,
  darkButtonPrimaryBackground: darkColors.darkButtonPrimaryBackground,
  darkButtonPrimaryText: darkColors.darkButtonPrimaryText,
  darkButtonSecondaryBackground: darkColors.darkButtonSecondaryBackground,
  darkButtonSecondaryText: darkColors.darkButtonSecondaryText,
  darkGreenBackgroundSolid: darkColors.darkGreenBackgroundSolid,
  darkGreenBackgroundTransparent: darkColors.darkGreenBackgroundTransparent,
  darkGreenBorder: darkColors.darkGreenBorder,
  darkGreenIcon: darkColors.darkGreenIcon,
  darkGreenText: darkColors.darkGreenText,
  darkRedBackgroundSolid: darkColors.darkRedBackgroundSolid,
  darkRedBackgroundTransparent: darkColors.darkRedBackgroundTransparent,
  darkRedBorder: darkColors.darkRedBorder,
  darkRedIcon: darkColors.darkRedIcon,
  darkRedText: darkColors.darkRedText,
  darkYellowBackgroundSolid: darkColors.darkYellowBackgroundSolid,
  darkYellowBackgroundTransparent: darkColors.darkYellowBackgroundTransparent,
  darkYellowBorder: darkColors.darkYellowBorder,
  darkYellowIcon: darkColors.darkYellowIcon,
  darkYellowText: darkColors.darkYellowText,
};
