import { darkColors, lightColors } from "@coral-xyz/themes";

import { tokens } from "./tokens";

export const color = {
  lightUser01: lightColors.lightUser01,
  lightUser02: lightColors.lightUser02,
  lightUser03: lightColors.lightUser03,
  lightUser04: lightColors.lightUser04,
  lightUser05: lightColors.lightUser05,
  lightUser06: lightColors.lightUser06,
  lightUser07: lightColors.lightUser07,
  lightUser08: lightColors.lightUser08,
  lightUser09: lightColors.lightUser09,
  lightUser10: lightColors.lightUser10,
  lightUser11: lightColors.lightUser11,
  lightUser12: lightColors.lightUser12,
  lightUser13: lightColors.lightUser13,
  lightUser14: lightColors.lightUser14,
  lightBaseBackgroundL0: lightColors.lightBaseBackgroundL0,
  lightBaseBackgroundL1: lightColors.lightBaseBackgroundL1,
  lightBaseBorderLight: lightColors.lightBaseBorderLight,
  lightBaseIcon: lightColors.lightBaseIcon,
  lightBaseIconHover: lightColors.lightBaseIconHover,
  lightBaseIconPress: lightColors.lightBaseIconPress,
  lightBaseTextHighEmphasis: lightColors.lightBaseTextHighEmphasis,
  lightBaseTextMedEmphasis: lightColors.lightBaseTextMedEmphasis,
  lightButtonPrimaryBackground: lightColors.lightButtonPrimaryBackground,
  lightButtonPrimaryText: lightColors.lightButtonPrimaryText,
  lightButtonSecondaryBackground: lightColors.lightButtonSecondaryBackground,
  lightButtonSecondaryText: lightColors.lightButtonSecondaryText,
  lightGreenBackgroundSolid: lightColors.lightGreenBackgroundSolid,
  // lightGreenBackgroundTransparent: lightColors.lightGreenBackgroundTransparent,
  // lightGreenBorder: lightColors.lightGreenBorder,
  lightGreenIcon: lightColors.lightGreenIcon,
  lightGreenText: lightColors.lightGreenText,
  lightRedBackgroundSolid: lightColors.lightRedBackgroundSolid,
  // lightRedBackgroundTransparent: lightColors.lightRedBackgroundTransparent,
  // lightRedBorder: lightColors.lightRedBorder,
  lightRedIcon: lightColors.lightRedIcon,
  lightRedText: lightColors.lightRedText,
  lightYellowBackgroundSolid: lightColors.lightYellowBackgroundSolid,
  // lightYellowBackgroundTransparent: lightColors.lightYellowBackgroundTransparent,
  // lightYellowBorder: lightColors.lightYellowBorder,
  lightYellowIcon: lightColors.lightYellowIcon,
  lightYellowText: lightColors.lightYellowText,

  darkUser01: darkColors.darkUser01,
  darkUser02: darkColors.darkUser02,
  darkUser03: darkColors.darkUser03,
  darkUser04: darkColors.darkUser04,
  darkUser05: darkColors.darkUser05,
  darkUser06: darkColors.darkUser06,
  darkUser07: darkColors.darkUser07,
  darkUser08: darkColors.darkUser08,
  darkUser09: darkColors.darkUser09,
  darkUser10: darkColors.darkUser10,
  darkUser11: darkColors.darkUser11,
  darkUser12: darkColors.darkUser12,
  darkUser13: darkColors.darkUser13,
  darkUser14: darkColors.darkUser14,

  darkBaseBackgroundL0: darkColors.darkBaseBackgroundL0,
  darkBaseBackgroundL1: darkColors.darkBaseBackgroundL1,
  // darkBaseBorderLight: darkColors.darkBaseBorderLight,
  darkBaseIcon: darkColors.darkBaseIcon,
  darkBaseIconHover: darkColors.darkBaseIconHover,
  darkBaseIconPress: darkColors.darkBaseIconPress,
  darkBaseTextHighEmphasis: darkColors.darkBaseTextHighEmphasis,
  darkBaseTextMedEmphasis: darkColors.darkBaseTextMedEmphasis,
  darkButtonPrimaryBackground: darkColors.darkButtonPrimaryBackground,
  darkButtonPrimaryText: darkColors.darkButtonPrimaryText,
  darkButtonSecondaryBackground: darkColors.darkButtonSecondaryBackground,
  darkButtonSecondaryText: darkColors.darkButtonSecondaryText,
  darkGreenBackgroundSolid: darkColors.darkGreenBackgroundSolid,
  // darkGreenBackgroundTransparent: darkColors.darkGreenBackgroundTransparent,
  // darkGreenBorder: darkColors.darkGreenBorder,
  darkGreenIcon: darkColors.darkGreenIcon,
  darkGreenText: darkColors.darkGreenText,
  darkRedBackgroundSolid: darkColors.darkRedBackgroundSolid,
  // darkRedBackgroundTransparent: darkColors.darkRedBackgroundTransparent,
  // darkRedBorder: darkColors.darkRedBorder,
  darkRedIcon: darkColors.darkRedIcon,
  darkRedText: darkColors.darkRedText,
  darkYellowBackgroundSolid: darkColors.darkYellowBackgroundSolid,
  // darkYellowBackgroundTransparent: darkColors.darkYellowBackgroundTransparent,
  // darkYellowBorder: darkColors.darkYellowBorder,
  darkYellowIcon: darkColors.darkYellowIcon,
  darkYellowText: darkColors.darkYellowText,
};

export const light = {
  baseBackgroundL1: tokens.color.lightBaseBackgroundL1,
  baseTextHighEmphasis: tokens.color.lightBaseTextHighEmphasis,
  baseTextMedEmphasis: tokens.color.lightBaseTextMedEmphasis,
  baseIcon: tokens.color.lightBaseIcon,
  baseIconHover: tokens.color.lightBaseIconHover,
  baseIconPress: tokens.color.lightBaseIconPress,
  baseBorderLight: tokens.color.lightBaseBorderLight,
  buttonPrimaryBackground: tokens.color.lightButtonPrimaryBackground,
  buttonPrimaryText: tokens.color.lightButtonPrimaryText,
  buttonSecondaryBackground: tokens.color.lightButtonSecondaryBackground,
  buttonSecondaryText: tokens.color.lightButtonSecondaryText,
  greenText: tokens.color.lightGreenText,
  greenIcon: tokens.color.lightGreenIcon,
  // greenBorder: tokens.color.lightGreenBorder,
  greenBackgroundSolid: tokens.color.lightGreenBackgroundSolid,
  // greenBackgroundTransparent: tokens.color.lightGreenBackgroundTransparent,
  yellowText: tokens.color.lightYellowText,
  yellowIcon: tokens.color.lightYellowIcon,
  // yellowBorder: tokens.color.lightYellowBorder,
  yellowBackgroundSolid: tokens.color.lightYellowBackgroundSolid,
  // yellowBackgroundTransparent: tokens.color.lightYellowBackgroundTransparent,
  redText: tokens.color.lightRedText,
  redIcon: tokens.color.lightRedIcon,
  // redBorder: tokens.color.lightRedBorder,
  redBackgroundSolid: tokens.color.lightRedBackgroundSolid,
  // redBackgroundTransparent: tokens.color.lightRedBackgroundTransparent,
};

export const dark = {
  baseBackgroundL1: tokens.color.darkBaseBackgroundL1,
  baseTextHighEmphasis: tokens.color.darkBaseTextHighEmphasis,
  baseTextMedEmphasis: tokens.color.darkBaseTextMedEmphasis,
  baseIcon: tokens.color.darkBaseIcon,
  baseIconHover: tokens.color.darkBaseIconHover,
  baseIconPress: tokens.color.darkBaseIconPress,
  // baseBorderdark: tokens.color.darkBaseBorderLight,
  buttonPrimaryBackground: tokens.color.darkButtonPrimaryBackground,
  buttonPrimaryText: tokens.color.darkButtonPrimaryText,
  buttonSecondaryBackground: tokens.color.darkButtonSecondaryBackground,
  buttonSecondaryText: tokens.color.darkButtonSecondaryText,
  greenText: tokens.color.darkGreenText,
  greenIcon: tokens.color.darkGreenIcon,
  // greenBorder: tokens.color.darkGreenBorder,
  greenBackgroundSolid: tokens.color.darkGreenBackgroundSolid,
  // greenBackgroundTransparent: tokens.color.darkGreenBackgroundTransparent,
  yellowText: tokens.color.darkYellowText,
  yellowIcon: tokens.color.darkYellowIcon,
  // yellowBorder: tokens.color.darkYellowBorder,
  yellowBackgroundSolid: tokens.color.darkYellowBackgroundSolid,
  // yellowBackgroundTransparent: tokens.color.darkYellowBackgroundTransparent,
  redText: tokens.color.darkRedText,
  redIcon: tokens.color.darkRedIcon,
  // redBorder: tokens.color.darkRedBorder,
  redBackgroundSolid: tokens.color.darkRedBackgroundSolid,
  // redBackgroundTransparent: tokens.color.darkRedBackgroundTransparent,
};
