import { color as color_, radius, size, space, zIndex } from "@tamagui/themes";
import { createTokens } from "tamagui";

import { color } from "./colors";

export const tokens = createTokens({
  color: {
    ...color_,
    ...color,
  },
  space: {
    ...space,
    settingsList: 12,
  },
  size: {
    ...size,
    xs: 12,
    sm: 14,
    md: 16,
    base: 16,
    true: 16, // true is always default
    lg: 18,
    xl: 20,
    "2xl": 24,
    "3xl": 28,
    "4xl": 32,
    "5xl": 36,
    "6xl": 40,
    borderWidth: 2,
    container: 56,
    input: 56,
    screen: 16,
    headerIcon: 24,
    screenPx: 16,
    screenPt: 16,
    screenPb: 16,
    settingsList: 12,
  },
  zIndex,
  radius: {
    ...radius,
    container: 12,
    large: 16,
    medium: 8,
    true: 16, // true is always default
    small: 4,
    circular: 1000,
  },
});

// The colors are tokenized so they can be utilized by the theme.
export const lightThemeColors = {
  blue100: tokens.color.blue100,
  blue800: tokens.color.blue800,
  modal: tokens.color.baseWhite,
  card: tokens.color.baseWhite,

  baseBackgroundL0: tokens.color.lightBaseBackgroundL0,
  baseBackgroundL1: tokens.color.lightBaseBackgroundL1,
  baseBackgroundL2: tokens.color.lightBaseBackgroundL2,
  baseTextHighEmphasis: tokens.color.lightBaseTextHighEmphasis,
  baseTextMedEmphasis: tokens.color.lightBaseTextMedEmphasis,
  baseIcon: tokens.color.lightBaseIcon,
  baseIconHover: tokens.color.lightBaseIconHover,
  baseIconPress: tokens.color.lightBaseIconPress,
  baseBorderLight: tokens.color.lightBaseBorderLight,
  baseBorderMed: tokens.color.lightBaseBorderMed,
  baseBorderFocus: tokens.color.darkBaseBorderFocus,
  baseDivider: tokens.color.darkBaseDivider,
  buttonPrimaryBackground: tokens.color.lightButtonPrimaryBackground,
  buttonPrimaryText: tokens.color.lightButtonPrimaryText,
  buttonSecondaryBackground: tokens.color.lightButtonSecondaryBackground,
  buttonSecondaryText: tokens.color.lightButtonSecondaryText,
  greenText: tokens.color.lightGreenText,
  greenIcon: tokens.color.lightGreenIcon,
  greenBorder: tokens.color.lightGreenBorder,
  greenBackgroundSolid: tokens.color.lightGreenBackgroundSolid,
  greenBackgroundTransparent: tokens.color.lightGreenBackgroundTransparent,
  yellowText: tokens.color.lightYellowText,
  yellowIcon: tokens.color.lightYellowIcon,
  yellowBorder: tokens.color.lightYellowBorder,
  yellowBackgroundSolid: tokens.color.lightYellowBackgroundSolid,
  yellowBackgroundTransparent: tokens.color.lightYellowBackgroundTransparent,
  redText: tokens.color.lightRedText,
  redIcon: tokens.color.lightRedIcon,
  redBorder: tokens.color.lightRedBorder,
  redBackgroundSolid: tokens.color.lightRedBackgroundSolid,
  redBackgroundTransparent: tokens.color.lightRedBackgroundTransparent,
  accentBlue: tokens.color.lightAccentBlue,
  accentBlueBackground: tokens.color.lightAccentBlueBackground,
  accentPurple: tokens.color.lightAccentPurple,

  // Inverted colors.
  invertedBaseBackgroundL0: tokens.color.darkBaseBackgroundL0,
  invertedBaseTextHighEmphasis: tokens.color.darkBaseTextHighEmphasis,
};

export const darkThemeColors = {
  blue100: tokens.color.blue100,
  blue800: tokens.color.blue800,
  modal: tokens.color.darkBaseBackgroundL0,
  card: tokens.color.darkBaseBackgroundL1,

  baseBackgroundL0: tokens.color.darkBaseBackgroundL0,
  baseBackgroundL1: tokens.color.darkBaseBackgroundL1,
  baseBackgroundL2: tokens.color.darkBaseBackgroundL2,
  baseTextHighEmphasis: tokens.color.darkBaseTextHighEmphasis,
  baseTextMedEmphasis: tokens.color.darkBaseTextMedEmphasis,
  baseIcon: tokens.color.darkBaseIcon,
  baseIconHover: tokens.color.darkBaseIconHover,
  baseIconPress: tokens.color.darkBaseIconPress,
  baseBorderLight: tokens.color.darkBaseBorderLight,
  baseBorderMed: tokens.color.darkBaseBorderMed,
  baseBorderFocus: tokens.color.darkBaseBorderFocus,
  baseDivider: tokens.color.darkBaseDivider,
  buttonPrimaryBackground: tokens.color.darkButtonPrimaryBackground,
  buttonPrimaryText: tokens.color.darkButtonPrimaryText,
  buttonSecondaryBackground: tokens.color.darkButtonSecondaryBackground,
  buttonSecondaryText: tokens.color.darkButtonSecondaryText,
  greenText: tokens.color.darkGreenText,
  greenIcon: tokens.color.darkGreenIcon,
  greenBorder: tokens.color.darkGreenBorder,
  greenBackgroundSolid: tokens.color.darkGreenBackgroundSolid,
  greenBackgroundTransparent: tokens.color.darkGreenBackgroundTransparent,
  yellowText: tokens.color.darkYellowText,
  yellowIcon: tokens.color.darkYellowIcon,
  yellowBorder: tokens.color.darkYellowBorder,
  yellowBackgroundSolid: tokens.color.darkYellowBackgroundSolid,
  yellowBackgroundTransparent: tokens.color.darkYellowBackgroundTransparent,
  redText: tokens.color.darkRedText,
  redIcon: tokens.color.darkRedIcon,
  redBorder: tokens.color.darkRedBorder,
  redBackgroundSolid: tokens.color.darkRedBackgroundSolid,
  redBackgroundTransparent: tokens.color.darkRedBackgroundTransparent,
  accentBlue: tokens.color.darkAccentBlue,
  accentBlueBackground: tokens.color.darkAccentBlueBackground,
  accentPurple: tokens.color.darkAccentPurple,

  // Inverted colors.
  invertedBaseBackgroundL0: tokens.color.lightBaseBackgroundL0,
  invertedBaseTextHighEmphasis: tokens.color.lightBaseTextHighEmphasis,
};
