import { size, space, zIndex } from "@tamagui/themes";
import { createTokens } from "tamagui";

import { color } from "./colors";

export const tokens = createTokens({
  color,
  space,
  size: {
    ...size,
    xs: 12,
    sm: 14,
    base: 16,
    true: 16, // true is always default
    lg: 18,
    xl: 20,
    "2xl": 24,
    "3xl": 28,
    "4xl": 32,
    "5xl": 36,
    "6xl": 40,
    borderWidth: 2,
    container: 56,
    input: 56,
    screen: 16,
    headerIcon: 24,
    screenPx: 16,
    screenPt: 16,
    screenPb: 16,
  },
  zIndex,
  radius: {
    container: 12,
    large: 16,
    medium: 8,
    true: 8, // true is always default
    small: 4,
    circular: "50%",
  },
});

// the colors are tokenized so they can be utilized by the theme
export const lightThemeColors = {
  modal: tokens.color.baseWhite,
  card: tokens.color.baseWhite,
  accentBlue: tokens.color.lightAccentBlue,
  accentPurple: tokens.color.lightAccentPurple,
  // old theme colors
  fontColor: tokens.color.lightBaseTextHighEmphasis,
  icon: tokens.color.lightBaseIcon,
  background: tokens.color.lightBaseBackgroundL0,
  negative: tokens.color.lightRedText,
  positive: tokens.color.lightGreenText,
  smallTextColor: tokens.color.lightBaseTextMedEmphasis,
  // nav,
  // secondary,
  // bg2,
  // bg3,
  textPlaceholder: tokens.color.lightBaseTextMedEmphasis,
  primaryButtonTextColor: tokens.color.lightButtonPrimaryText,
  secondaryButtonTextColor: tokens.color.lightButtonSecondaryText,
  primaryButton: tokens.color.lightButtonPrimaryBackground,
  secondaryButton: tokens.color.lightButtonSecondaryBackground,
  textInputBorderFull: tokens.color.lightBaseBorderLight,
  borderFull: tokens.color.lightBaseBorderLight,
  borderColor: tokens.color.lightBaseBorderLight,

  // new theme colors
  baseBackgroundL1: tokens.color.lightBaseBackgroundL1,
  baseTextHighEmphasis: tokens.color.lightBaseTextHighEmphasis,
  baseTextMedEmphasis: tokens.color.lightBaseTextMedEmphasis,
  baseIcon: tokens.color.lightBaseIcon,
  baseIconHover: tokens.color.lightBaseIconHover,
  baseIconPress: tokens.color.lightBaseIconPress,
  baseBorderLight: tokens.color.lightBaseBorderLight,
  buttonPrimaryBackground: tokens.color.lightButtonPrimaryBackground,
  buttonPrimaryText: tokens.color.lightButtonPrimaryText,
  buttonSecondaryBackground: tokens.color.lightButtonSecondaryBackground,
  buttonSecondaryText: tokens.color.lightButtonSecondaryText,
  greenText: tokens.color.lightGreenText,
  greenIcon: tokens.color.lightGreenIcon,
  greenBorder: tokens.color.lightGreenBorder,
  greenBackgroundSolid: tokens.color.lightGreenBackgroundSolid,
  greenBackgroundTransparent: tokens.color.lightGreenBackgroundTransparent,
  yellowText: tokens.color.lightYellowText,
  yellowIcon: tokens.color.lightYellowIcon,
  yellowBorder: tokens.color.lightYellowBorder,
  yellowBackgroundSolid: tokens.color.lightYellowBackgroundSolid,
  yellowBackgroundTransparent: tokens.color.lightYellowBackgroundTransparent,
  redText: tokens.color.lightRedText,
  redIcon: tokens.color.lightRedIcon,
  redBorder: tokens.color.lightRedBorder,
  redBackgroundSolid: tokens.color.lightRedBackgroundSolid,
  redBackgroundTransparent: tokens.color.lightRedBackgroundTransparent,
};

export const darkThemeColors = {
  modal: tokens.color.darkBaseBackgroundL0,
  card: tokens.color.darkBaseBackgroundL0,
  accentBlue: tokens.color.darkAccentBlue,
  accentPurple: tokens.color.darkAccentPurple,
  // old theme colors
  fontColor: tokens.color.darkBaseTextHighEmphasis,
  icon: tokens.color.darkBaseIcon,
  background: tokens.color.darkBaseBackgroundL0,
  negative: tokens.color.darkRedText,
  positive: tokens.color.darkGreenText,
  smallTextColor: tokens.color.darkBaseTextMedEmphasis,
  // nav,
  // secondary,
  // bg2,
  // bg3,
  textPlaceholder: tokens.color.darkBaseTextMedEmphasis,
  primaryButtonTextColor: tokens.color.darkButtonPrimaryText,
  secondaryButtonTextColor: tokens.color.darkButtonSecondaryText,
  primaryButton: tokens.color.darkButtonPrimaryBackground,
  secondaryButton: tokens.color.darkButtonSecondaryBackground,
  textInputBorderFull: tokens.color.darkBaseBorderLight,
  borderFull: tokens.color.darkBaseBorderLight,
  borderColor: tokens.color.darkBaseBorderLight,

  // new theme colors
  baseBackgroundL1: tokens.color.darkBaseBackgroundL1,
  baseTextHighEmphasis: tokens.color.darkBaseTextHighEmphasis,
  baseTextMedEmphasis: tokens.color.darkBaseTextMedEmphasis,
  baseIcon: tokens.color.darkBaseIcon,
  baseIconHover: tokens.color.darkBaseIconHover,
  baseIconPress: tokens.color.darkBaseIconPress,
  baseBorderLight: tokens.color.darkBaseBorderLight,
  buttonPrimaryBackground: tokens.color.darkButtonPrimaryBackground,
  buttonPrimaryText: tokens.color.darkButtonPrimaryText,
  buttonSecondaryBackground: tokens.color.darkButtonSecondaryBackground,
  buttonSecondaryText: tokens.color.darkButtonSecondaryText,
  greenText: tokens.color.darkGreenText,
  greenIcon: tokens.color.darkGreenIcon,
  greenBorder: tokens.color.darkGreenBorder,
  greenBackgroundSolid: tokens.color.darkGreenBackgroundSolid,
  greenBackgroundTransparent: tokens.color.darkGreenBackgroundTransparent,
  yellowText: tokens.color.darkYellowText,
  yellowIcon: tokens.color.darkYellowIcon,
  yellowBorder: tokens.color.darkYellowBorder,
  yellowBackgroundSolid: tokens.color.darkYellowBackgroundSolid,
  yellowBackgroundTransparent: tokens.color.darkYellowBackgroundTransparent,
  redText: tokens.color.darkRedText,
  redIcon: tokens.color.darkRedIcon,
  redBorder: tokens.color.darkRedBorder,
  redBackgroundSolid: tokens.color.darkRedBackgroundSolid,
  redBackgroundTransparent: tokens.color.darkRedBackgroundTransparent,
};
