-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."secure_transfer_transactions" add column "message_id" text
--  not null;
